import type { Turf } from "@/types/turf";

export const mockTurfs: Turf[] = [
  {
    _id: "1",
    name: "Champion Futsal Arena",
    location: "Agrabad, Chattogram",
    pricePerHour: 800,
    sportType: "futsal",
    images: ["/turfs/futsal-1.jpg"],
    rating: 4.5,
    isAvailable: true,
    description: "Premium indoor futsal turf with synthetic grass and floodlights.",
    ownerId: "owner1",
    createdAt: "2026-01-10T10:00:00Z",
  },
  {
    _id: "2",
    name: "GEC Cricket Ground",
    location: "GEC Circle, Chattogram",
    pricePerHour: 1200,
    sportType: "cricket",
    images: ["/turfs/cricket-1.jpg"],
    rating: 4.2,
    isAvailable: true,
    description: "Full-size cricket ground with practice nets and pavilion.",
    ownerId: "owner2",
    createdAt: "2026-01-11T10:00:00Z",
  },
  {
    _id: "3",
    name: "Smash Badminton Court",
    location: "Nasirabad, Chattogram",
    pricePerHour: 500,
    sportType: "badminton",
    images: ["/turfs/badminton-1.jpg"],
    rating: 4.7,
    isAvailable: false,
    description: "Air-conditioned indoor badminton court with wooden flooring.",
    ownerId: "owner1",
    createdAt: "2026-01-12T10:00:00Z",
  },
];